// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lib_manager.Database;

namespace lib_manager.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20210523223325_FixReservationTypes")]
    partial class FixReservationTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("lib_manager.Models.UserModel", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.HasKey("username");

                    b.ToTable("UserList");

                    b.HasData(
                        new
                        {
                            username = "test1@gmail.com",
                            password = "123",
                            role = 0
                        },
                        new
                        {
                            username = "thepope@gmail.com",
                            password = "blessyou",
                            role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
