name: Building and testing

on:
  push:
    branches-ignore: [ master ]
  
env:
  NETCORE_VERSION: '5.0'
  NODE_VERSION: 14.x

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm ci and test
        run: |
          cd lib-manager-ui
          npm ci
          npm test
      - name: Restore .net packages
        run: |
          cd lib-manager-tests
          dotnet restore
      - name: Test app
        run: |
          cp -R lib-manager-ui/ lib-manager-service/ClientApp/
          cd lib-manager-tests
          dotnet test
